### ISSUE TITLE
Invalid User Agent

### ISSUE THREAD

**Issue by djsnipa1** [aiocat/ripgvc#2]
It is showing “Invalid User Agent” 

![4DBDCFD1-1E05-46B3-AFDE-7BE187333576](https://user-images.githubusercontent.com/118037/175210788-f11b4f2a-4dfc-4afa-91d0-bc4e6454ce3d.jpeg)

Here is my code:

```markdown 
![](https://ripgvc.herokuapp.com/?username=djsnipa1&color=e64f00&round)
```

**Comment by aiocat** [comment]
Where di you tried to use this badge? This badge only works in GitHub README's
